name = "Modpack"
author = "Jan Bulthuis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab2fd4f35ca76d43d2d93e58980c7c8c42b3e852d406e7a7079e61176337edf0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
