name = "Modpack"
author = "Jan Bulthuis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "419511d38974f895612f577de3d4f0d4b06c2b364af630ccec0dbc23201cdeb4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
