name = "Modpack"
author = "Jan Bulthuis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28470e3a97293365aa66a840fdaa977b6369ab2d7fc388eadf9c9ae4aa47c4a2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
