enable_system_global_packs = false

[resourcepacks]
required = ["global_packs/required_resources/"]

[datapacks]
required = ["resourcepacks/", "global_packs/required_data/"]
optional = ["global_packs/optional_data/"]
